# Generated by Django 3.2.13 on 2022-05-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrito',
            old_name='distrito',
            new_name='provincia',
        ),
    ]
