# Generated by Django 3.2.13 on 2022-05-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0002_rename_distrito_distrito_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assistencia_tecnica.sector'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='assistencia_tecnica.provincia'),
        ),
        migrations.AlterField(
            model_name='fichaassistenciatecnica',
            name='health_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.healthfacility'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facilities', to='assistencia_tecnica.distrito'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='assistencia_tecnica.area'),
        ),
    ]
