# Generated by Django 3.2.13 on 2022-05-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0003_auto_20220515_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_sanitarias', to='assistencia_tecnica.distrito')),
            ],
        ),
        migrations.RemoveField(
            model_name='fichaassistenciatecnica',
            name='health_facility',
        ),
        migrations.DeleteModel(
            name='HealthFacility',
        ),
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='unidades_sanitaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.unidadesanitaria'),
            preserve_default=False,
        ),
    ]
