# Generated by Django 3.2.13 on 2022-05-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0004_auto_20220515_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadesanitaria',
            old_name='name',
            new_name='nome',
        ),
    ]
