# Generated by Django 3.2.13 on 2022-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0005_rename_name_unidadesanitaria_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaassistenciatecnica',
            name='indicador',
        ),
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='indicadores',
            field=models.ManyToManyField(to='assistencia_tecnica.Indicador'),
        ),
    ]
