# Generated by Django 3.2.13 on 2022-05-16 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistencia_tecnica', '0008_auto_20220516_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='feito_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='feito_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='user.user'),
            preserve_default=False,
        ),
    ]
