# Generated by Django 3.2.15 on 2022-09-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia_tecnica', '0009_auto_20220516_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=255),
        ),
    ]
