# Generated by Django 3.2.14 on 2022-08-02 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('stock', models.IntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('quantidade_necessaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
       
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('feito_em', models.DateTimeField(auto_now=True)),
                ('status_requisicao', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=50)),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector')),
            ],
            options={
                'verbose_name': 'Requisicao',
                'verbose_name_plural': 'Requisicoes',
            },
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('quantidade', models.IntegerField()),
                ('feito_em', models.DateTimeField(auto_now=True)),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector')),
            ],
        ),
        migrations.AddField(
            model_name='instrumento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='si_stock.provincia'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='si_stock.sector'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('fornecedor', models.CharField(choices=[('ECHO', 'ECHO'), ('MISAU', 'MISAU'), ('LEVANTAMENTO DEPOSITO', 'LEVANTAMENTO NO DEPOSITO')], max_length=100)),
                ('quantidade', models.IntegerField()),
                ('feito_em', models.DateTimeField(auto_now=True)),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aprovacao', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('feito_em', models.DateTimeField(auto_now=True)),
                ('feito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.requisicao')),
            ],
            options={
                'verbose_name': 'Aprovacao',
                'verbose_name_plural': 'Aprovacoes',
            },
        ),
    ]
