# Generated by Django 3.2.15 on 2022-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=255, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('necessidade', models.IntegerField(blank=True, null=True)),
                ('requisicao_id', models.IntegerField(blank=True, null=True)),
                ('data_requisicao', models.DateField(blank=True, null=True)),
                ('quantidade_requisicao', models.IntegerField(blank=True, null=True)),
                ('status_requisicao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Resumo de Instrumento',
                'verbose_name_plural': 'Resumo de Instrumentos',
            },
        ),
    ]
