# Generated by Django 4.0.3 on 2022-04-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('openmrs', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
                ('attributeOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('openmrs_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
                ('healthfacility_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openmrs_designation', models.CharField(max_length=100)),
                ('dhis_designation', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('M', 'Mensal'), ('Q', 'Trimestral'), ('S', 'Semestral'), ('A', 'Anual')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
        migrations.CreateModel(
            name='DataElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('dataElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataelement')),
                ('healthFacility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.healthfacility')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
        ),
        migrations.AddField(
            model_name='dataelement',
            name='dataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset'),
        ),
    ]
