# Generated by Django 4.0.3 on 2022-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_openmrs_code_healthfacility_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='id',
        ),
        migrations.AlterField(
            model_name='period',
            name='openmrs_designation',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
