# Generated by Django 4.0.3 on 2022-04-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportmonth_reportperiodtype_reportyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelementvalue',
            name='periodperiod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.reportperiod'),
            preserve_default=False,
        ),
    ]
