# Generated by Django 4.0.3 on 2022-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_txcurrnewpvlsmonth_txcurrnewpvlstrim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txcurrnewpvlsmonth',
            old_name='element',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='txcurrnewpvlstrim',
            old_name='element',
            new_name='code',
        ),
        migrations.AddField(
            model_name='txcurrnewpvlsmonth',
            name='dataelement',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txcurrnewpvlstrim',
            name='dataelement',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
