# Generated by Django 4.0.4 on 2022-05-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dataelementvalue_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='openmrs',
        ),
    ]
