# Generated by Django 3.2.14 on 2022-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('last_appointment_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=150, null=True)),
                ('community', models.CharField(blank=True, max_length=500, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=10, null=True)),
                ('drug_pickup_missed_days', models.IntegerField(blank=True, default=0, null=True)),
                ('visit_missed_days', models.IntegerField(blank=True, default=0, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(max_length=150)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('appointment_date', models.DateField()),
                ('next_appointment_date', models.DateField()),
                ('gender', models.CharField(max_length=150)),
                ('community', models.CharField(blank=True, max_length=500, null=True)),
                ('pregnant', models.CharField(default='NAO', max_length=10)),
                ('brestfeeding', models.CharField(default='NAO', max_length=10)),
                ('tb', models.CharField(default='NAO', max_length=10)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
