# Generated by Django 3.2.16 on 2023-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_viamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_value', models.CharField(max_length=255)),
            ],
        ),
    ]
