# Generated by Django 3.2.13 on 2022-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_viamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedappointment',
            name='drug_pickup_missed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missedappointment',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missedappointment',
            name='visit_missed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
