# Generated by Django 3.2.13 on 2022-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_viamo', '0002_auto_20220508_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missedappointment',
            name='brestfeeding',
        ),
    ]
