# Generated by Django 3.2.13 on 2022-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_viamo', '0005_auto_20220508_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedappointment',
            name='drug_pickup_missed_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='missedappointment',
            name='last_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missedappointment',
            name='pregnant',
            field=models.CharField(blank=True, default='NAO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='missedappointment',
            name='visit_missed_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
