# Generated by Django 3.2.13 on 2022-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_viamo', '0006_auto_20220508_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedappointment',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
